[workspace]
resolver = "2"
members = ["egui_wgpu_grapher", "gpu_finite_difference"]
default-members = ["egui_wgpu_grapher"]

[workspace.dependencies]
bytemuck = "1.23.2"
egui = "0.35"
egui-wgpu = { version = "0.35", features = ["winit"] }
egui-winit = "0.35"
pollster = "0.4.0"
winit = "0.30.12"

[workspace.dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
