#!/usr/bin/env bash

# turn on env_log logging
export RUST_LOG=wgpu_grapher=info

if [[ "$1" != "debug" && "$1" != "release" ]]; then
  echo "Required arg: debug or release."
  exit 2
fi

target/$1/wgpu_grapher

